---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asciiflow
spec:
  selector:
    matchLabels:
      app: asciiflow
  replicas: 1
  template:
    metadata:
      labels:
        app: asciiflow
    spec:
      containers:
        - name: asciiflow
          image: ryodocx/asciiflow2
          ports:
            - containerPort: 80
